---
- name: Install NGINX & modules
  package:
    name:
      - nginx
      - libnginx-mod-http-lua
      - libnginx-mod-http-geoip
    state: present
  tags:
    - role::nginx

- name: Copy NGINX default config
  copy:
    src: default_server.conf
    dest: /etc/nginx/conf.d/default_server.conf
    group: root
    owner: root
    mode: 0644
  tags:
    - role::nginx
  notify:
    - reload the nginx service
