apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-secret: "kube-system/mtls-client-crt-bundle"
    nginx.ingress.kubernetes.io/auth-tls-error-page: "https://maintenance.python-discord.workers.dev/"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "AlertManager_LB"
    nginx.ingress.kubernetes.io/session-cookie-domain: "alertmanager.pydis.wtf"
    nginx.ingress.kubernetes.io/session-cookie-samesite: "Strict"
    nginx.ingress.kubernetes.io/session-cookie-expires: "3600"
  name: alertmanager
  namespace: monitoring
spec:
  tls:
  - hosts:
      - "*.pydis.wtf"
    secretName: pydis.wtf-tls
  rules:
  - host: alertmanager.pydis.wtf
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: alertmanager
            port:
              number: 9093
