- name: Deploy common services
  hosts: all
  roles:
    - common
    - ufw
    # - prometheus-node-exporter
    - fail2ban

- name: Deploy Kubernetes control plane firewall rules
  hosts: kube_control_plane
  roles:
    - ufw-kubernetes-control-plane

- name: Deploy Kubernetes worker node firewall rules
  hosts: "{{ groups['kube_node'] | reject('eq', groups['kube_control_plane']) }}"
  roles:
    - ufw-kubernetes-worker-node

# - name: Deploy Kubernetes
#   import_playbook: kubespray/cluster.yml

# - name: Deploy our monitoring stack
#   hosts: ritchie
#   roles:
#     - prometheus
#
# - name: Deploy our PostgreSQL database hosts
#   hosts: lovelace
#   roles:
#     - postgres
