---
- name: Install Dovecot packages
  package:
    state: present
    name:
      - dovecot-core
      - dovecot-imapd
      - dovecot-lmtpd
      - dovecot-ldap
  tags:
    - role::dovecot

- name: Create the vmail group
  group:
    name: vmail
    state: present
    gid: 5000
  tags:
    - role::dovecot

- name: Create the vmail user
  user:
    name: vmail
    uid: 5000
    group: vmail
    home: /var/vmail
  tags:
    - role::dovecot

- name: Template Dovecot configuration
  template:
    src: dovecot.conf.j2
    dest: /etc/dovecot/dovecot.conf
    group: root
    owner: root
    mode: "0644"
  tags:
    - role::dovecot
  notify:
    - Reload Dovecot

- name: Template Dovecot LDAP config
  template:
    src: dovecot-ldap.conf.ext.j2
    dest: /etc/dovecot/dovecot-ldap.conf.ext
    group: root
    owner: root
    mode: "0600"
  tags:
    - role::dovecot
  notify:
    - Reload Dovecot

- name: Template Dovecot component configurations
  template:
    src: "configs/{{ item }}.j2"
    dest: "/etc/dovecot/conf.d/{{ item }}"
    group: root
    owner: root
    mode: "0644"
  loop:
    - 10-mail.conf
    - 10-master.conf
    - 10-auth.conf
    - 10-ssl.conf
    - 15-mailboxes.conf
    - auth-ldap.conf.ext
  tags:
    - role::dovecot
  notify:
    - Reload Dovecot
