---
- name: Install Dovecot packages
  package:
    state: present
    name:
      - dovecot-core
      - dovecot-imapd
      - dovecot-lmtpd
      - dovecot-ldap
      - dovecot-sieve
      - dovecot-managesieved
  tags:
    - role::dovecot

- name: Create the vmail group
  group:
    name: vmail
    state: present
    gid: 5000
  tags:
    - role::dovecot

- name: Create the vmail user
  user:
    name: vmail
    uid: "{{ dovecot_vmail_uid }}"
    group: vmail
    home: /var/vmail
  tags:
    - role::dovecot

- name: Copy welcome script
  copy:
    src: welcome.sh
    dest: /etc/dovecot/welcome.sh
    mode: "0744"
    owner: dovecot
    group: dovecot
  tags:
    - role::dovecot

- name: Template Dovecot configuration
  template:
    src: dovecot.conf.j2
    dest: /etc/dovecot/dovecot.conf
    group: root
    owner: root
    mode: "0644"
  tags:
    - role::dovecot
  notify:
    - Reload Dovecot

- name: Create sieve-after directory
  file:
    state: directory
    path: /etc/dovecot/sieve-after
    owner: vmail
    group: vmail
    mode: "0755"
  tags:
    - role::dovecot

- name: Template spam-to-folder sieve script
  template:
    src: spam-to-folder.sieve.j2
    dest: /etc/dovecot/sieve-after/spam-to-folder.sieve
    owner: vmail
    group: vmail
    mode: 0444
  notify:
    - Recompile spam-to-folder sieve script
  tags:
    - role::dovecot

- name: Set up sieve configuration for dovecot
  lineinfile:
    path: /etc/dovecot/conf.d/90-sieve.conf
    regexp: "sieve_after ="
    line: "  sieve_after = /etc/dovecot/sieve-after  # (ansible managed)"
    state: present
  notify:
    - Reload Dovecot
  tags:
    - role::dovecot

- name: Template Dovecot LDAP config
  template:
    src: dovecot-ldap.conf.ext.j2
    dest: /etc/dovecot/dovecot-ldap.conf.ext
    group: root
    owner: root
    mode: "0600"
  tags:
    - role::dovecot
  notify:
    - Reload Dovecot

- name: Template Dovecot component configurations
  template:
    src: "configs/{{ item }}.j2"
    dest: "/etc/dovecot/conf.d/{{ item }}"
    group: root
    owner: root
    mode: "0644"
  loop:
    - 10-mail.conf
    - 10-master.conf
    - 10-auth.conf
    - 10-ssl.conf
    - 15-mailboxes.conf
    - 20-lmtp.conf
    - auth-ldap.conf.ext
  tags:
    - role::dovecot
  notify:
    - Reload Dovecot
