---
- name: Reload postfix
  service:
    name: postfix
    state: reloaded

- name: Restart postfix
  service:
    name: postfix
    state: restarted

- name: Regenerate virtual table
  command: postmap /etc/postfix/virtual
  changed_when: true

- name: Regenerate transport table
  command: postmap /etc/postfix/transport
  changed_when: true

- name: Regenerate sender access table
  command: postmap /etc/postfix/sender_access
  changed_when: true
