apiVersion: v1
kind: Service
metadata:
  name: statsd-exporter
  namespace: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9102"
spec:
  selector:
    app: statsd-exporter
  ports:
    - name: prom-scrape
      protocol: TCP
      port: 9102
      targetPort: prom-scrape
    - name: statsd-udp
      protocol: UDP
      port: 8125
      targetPort: statsd-udp
    - name: statsd-tcp
      protocol: TCP
      port: 8125
      targetPort: statsd-tcp
