all:
  hosts:
    turing:
      ansible_host: turing.box.pydis.wtf
      wireguard_subnet: 10.1.0.0/16
    lovelace:
      ansible_host: lovelace.box.pydis.wtf
      wireguard_subnet: 10.2.0.0/16
    nginx:
      hosts:
        turing:
  vars:
    wireguard_port: 46850
