apiVersion: gateway.nginx.org/v1alpha2
kind: NginxProxy
metadata:
  name: nginx-proxy-config
  namespace: nginx-gateway
spec:
  rewriteClientIP:
    mode: XForwardedFor
    setIPRecursively: true
    trustedAddresses:
      # Cloudflare IPv4
      - type: CIDR
        value: "173.245.48.0/20"
      - type: CIDR
        value: "103.21.244.0/22"
      - type: CIDR
        value: "103.22.200.0/22"
      - type: CIDR
        value: "103.31.4.0/22"
      - type: CIDR
        value: "141.101.64.0/18"
      - type: CIDR
        value: "108.162.192.0/18"
      - type: CIDR
        value: "190.93.240.0/20"
      - type: CIDR
        value: "188.114.96.0/20"
      - type: CIDR
        value: "197.234.240.0/22"
      - type: CIDR
        value: "198.41.128.0/17"
      - type: CIDR
        value: "162.158.0.0/15"
      - type: CIDR
        value: "104.16.0.0/13"
      - type: CIDR
        value: "104.24.0.0/14"
      - type: CIDR
        value: "172.64.0.0/13"
      - type: CIDR
        value: "131.0.72.0/22"
      # Cloudflare IPv6
      - type: CIDR
        value: "2400:cb00::/32"
      - type: CIDR
        value: "2606:4700::/32"
      - type: CIDR
        value: "2803:f800::/32"
      - type: CIDR
        value: "2405:b500::/32"
      - type: CIDR
        value: "2405:8100::/32"
      - type: CIDR
        value: "2a06:98c0::/29"
      - type: CIDR
        value: "2c0f:f248::/32"
