certGenerator:
  agentTLSSecretName: "agent-tls"
  serverTLSSecretName: "server-tls"
  enable: false

nginxGateway:
  snippets:
    enable: true

nginx:
  kind: "daemonSet"

  pod:
    volumes:
      - name: mtls-client-crt-bundle
        configMap:
          name: mtls-client-crt-bundle

  container:
    volumeMounts:
      - name: mtls-client-crt-bundle
        mountPath: /etc/nginx/mtls-ca.crt
        subPath: ca.crt
