apiVersion: gateway.nginx.org/v1alpha1
kind: SnippetsFilter
metadata:
  name: alertmanager-sticky-session
  namespace: nginx-gateway
spec:
  snippets:
    - context: http.server.location
      value: |
        sticky cookie AlertManager_LB expires=1h domain=alertmanager.pydis.wtf path=/ samesite=strict;
