apiVersion: gateway.nginx.org/v1alpha1
kind: SnippetsPolicy
metadata:
  name: nginx-gateway-mtls
  namespace: nginx-gateway
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: nginx
  snippets:
    - context: http.server
      value: |
        ssl_client_certificate /etc/nginx/mtls-ca.crt;
        ssl_verify_client optional;
        ssl_verify_depth 1;
---
apiVersion: gateway.nginx.org/v1alpha1
kind: SnippetsFilter
metadata:
  name: enforce-mtls
  namespace: nginx-gateway
spec:
  snippets:
    - context: http.server.location
      value: |
        if ($ssl_client_verify != "SUCCESS") {
          return 302 https://maintenance.python-discord.workers.dev/;
        }
