---
- name: Reload Dovecot
  service:
    name: dovecot
    state: reloaded

- name: Restart Dovecot
  service:
    name: dovecot
    state: restarted

- name: Recompile spam-to-folder sieve script
  command: /usr/bin/sievec /etc/dovecot/sieve-after/spam-to-folder.sieve
  changed_when: true
