all:
  hosts:
    turing:
      ansible_host: turing.box.pydis.wtf
      wireguard_subnet: 10.1.0.0/16
    lovelace:
      ansible_host: lovelace.box.pydis.wtf
      wireguard_subnet: 10.2.0.0/16
    ldap01:
      ansible_host: ldap01.box.pydis.wtf
  children:
    netcup:
      hosts:
        turing:
        lovelace:
    nginx:
      hosts:
        turing:
        lovelace:
    databases:
      hosts:
        lovelace:
    monitoring:
      hosts:
        lovelace:
    ldap:
      hosts:
        ldap01:
  vars:
    wireguard_port: 46850
