all:
  hosts:
    lovelace:
      ansible_host: lovelace.box.pydis.wtf
      wireguard_subnet: 10.2.0.0/16
    ldap01:
      ansible_host: ldap01.box.pydis.wtf
  children:
    netcup:
      hosts:
        lovelace:
    nginx:
      hosts:
        lovelace:
    databases:
      hosts:
        lovelace:
    monitoring:
      hosts:
        lovelace:
    ldap:
      hosts:
        ldap01:
    mail:
      hosts:
        lovelace:
  vars:
    wireguard_port: 46850
