apiVersion: v1
kind: ConfigMap
metadata:
  name: sir-robin-config-env
  namespace: bots
data:
  AOC_YEAR: '2024'
  BOT_DEBUG: 'False'
  CATEGORY_SUMMER_CODE_JAM: '1397217460255588493'
  CHANNEL_ADVENT_OF_CODE_ANNOUNCE: '1312400095123341465'
  CHANNEL_SUMMER_CODE_JAM_ANNOUNCEMENTS: '1397217539972665344'
  ROLE_CODE_JAM_PARTICIPANTS: '991678713093705781'
