---
collections:
  - name: ansible.posix
    version: 1.6.2
  - name: community.crypto
    version: 2.23.0
  - name: community.general
    version: 9.5.3
  - name: community.postgresql
    version: 3.9.1

roles:
  - name: dmarc_metrics_exporter
    src: https://github.com/jgosmann/dmarc-metrics-exporter.git
