# We are deploying a replicated single binary (not components)
deploymentMode: SingleBinary

loki:
  # Disable authentication, we are in-cluster
  auth_enabled: false

  # Set replication to 3 replicas
  commonConfig:
    replication_factor: 3

  # We have one schemaConfig, storing data in TSDB format in S3
  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: index_
          period: 24h

  # Storage type is S3 (Linode Object Storage)
  storage:
    bucketNames:
      chunks: loki-cache-chunks
    type: s3
    s3:
      endpoint: eu-central-1.linodeobjects.com
      region: eu-central-1
      accessKeyId: ${AWS_ACCESS_KEY_ID}
      secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
      s3ForcePathStyle: true

  ingester:
    wal:
      flush_on_shutdown: true
    # Flush a chunk after this long with no new writes (even if not full)
    chunk_idle_period: 3h
    # Max age for any chunk regardless of activity
    max_chunk_age: 6h
    chunk_target_size: 10485760  # 10MB
    chunk_encoding: snappy

  compactor:
    retention_enabled: true
    delete_request_store: s3
    compaction_interval: 10m
    delete_request_cancel_period: 10s
    retention_delete_worker_count: 150
    retention_delete_delay: 10s

  limits_config:
    retention_period: 90d
    deletion_mode: filter-and-delete
    allow_deletes: true
    # Enable volume querying endpoint (for Grafana Explore Logs)
    volume_enabled: true
    retention_stream:
    - selector: '{app_container="/loki"}'
      priority: 1
      period: 14d
    - selector: '{app_container="/nginx", namespace="nginx-gateway"}'
      priority: 2
      period: 180d
    - selector: '{namespace="bots"}'
      priority: 3
      period: 180d
    - selector: '{namespace="web"}'
      priority: 4
      period: 180d
    - selector: '{job="ansible_dirsrv_access"}'
      priority: 5
      period: 1d

  # Enable ruler, writing to Prometheus
  rulerConfig:
    external_url: https://grafana.pydis.wtf
    datasource_uid: 4C7gKGxGk

    wal:
      dir: /var/loki/ruler-wal
    storage:
      # Set this to local, configMap rules do not seem to work with S3 storage https://github.com/grafana/loki/issues/12967#issuecomment-2614050185
      type: local
      local:
        directory: /rules
    enable_api: true
    enable_alertmanager_v2: true
    alertmanager_url: http://alertmanager.monitoring.svc:9093
    remote_write:
      enabled: true
      client:
        url: http://prometheus.monitoring.svc:9090/api/v1/write
    rule_path: /var/loki/ruler-scratch
    enable_sharding: true
    ring:
      kvstore:
        store: memberlist

sidecar:
  disableX509StrictVerification: true
  rules:
    enabled: true
    label: loki_rule
    labelValue: "yes"
    folder: /rules/fake

singleBinary:
  # Set replicas to 3 again
  replicas: 3
  # Inject Linode Object Storage credentials from secret
  extraEnvFrom:
    - secretRef:
        name: loki-s3
  # Disable any persistence in Loki, all persistence is in S3
  persistence:
    enabled: false
  extraArgs:
  # Enable the pattern ingester (for Grafana Explore Logs)
    - "--pattern-ingester.enabled=true"
  # Enable environment variable expansion in the Loki config (required for ${VAR} credential references)
    - "--config.expand-env=true"

  # Add a tmpfs in /var/loki for temporary data storage
  extraVolumes:
    - name: var-loki-tmpfs
      emptyDir:
        medium: Memory
    - name: rules
      emptyDir: {}
  extraVolumeMounts:
    - name: var-loki-tmpfs
      mountPath: /var/loki
    - name: rules
      mountPath: /rules

  # Add labels to enable Prometheus scraping of Loki replicas
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "http-metrics"

# Reduce the memory on the memcached cluster (defaults to 8GB)
chunksCache:
  allocatedMemory: 1024

# Scale the scalable replicas to 0 since we deploy single binary
read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0

# Enable Prometheus scraping of the Loki Canaries
lokiCanary:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "http-metrics"
