---
- name: Install pg_repack
  apt:
    name:
      - postgresql-{{ postgres_version }}-repack
    state: present
  tags:
    - role::postgres
    - role::postgres-pg_repack

- name: Add pg_repack to all databases
  become: true
  become_user: "{{ postgres_user }}"
  community.postgresql.postgresql_ext:
    db: "{{ item.name }}"
    name: pg_repack
    state: present
  loop: "{{ postgres_databases }}"
  tags:
    - role::postgres
    - role::postgres-pg_repack

- name: Add cronjob for running pg_repack on all databases
  cron:
    name: "Run pg_repack on all databases"
    special_time: "weekly"
    job: "pg_repack -a"
    user: "{{ postgres_user }}"
    cron_file: "{{ postgres_pg_repack_cron_filename }}"
  tags:
    - role::postgres
    - role::postgres-pg_repack
