- name: Reload ssh
  service:
    name: ssh
    state: reloaded
  tags:
    - role::common

- name: Restart systemd-timesyncd
  service:
    name: systemd-timesyncd
    state: restarted
  tags:
    - role::common
