apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: databases
data:
  postgresql.conf: |
    # From pgtune https://pgtune.leopard.in.ua/
    # DB Version: 16
    # OS Type: linux
    # DB Type: web
    # Total Memory (RAM): 6 GB
    # CPUs num: 4
    # Connections num: 110
    # Data Storage: ssd

    max_connections = 110
    shared_buffers = 1536MB
    effective_cache_size = 4608MB
    maintenance_work_mem = 384MB
    checkpoint_completion_target = 0.9
    wal_buffers = 16MB
    default_statistics_target = 100
    random_page_cost = 1.1
    effective_io_concurrency = 200
    work_mem = 7149kB
    huge_pages = off
    min_wal_size = 1GB
    max_wal_size = 4GB
    max_worker_processes = 4
    max_parallel_workers_per_gather = 2
    max_parallel_workers = 4
    max_parallel_maintenance_workers = 2

    # Custom conf
    listen_addresses = '*'
    password_encryption = md5
    shared_preload_libraries = 'pg_stat_statements'	# (change requires restart)
