kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-storage
  labels:
    app: postgres
  namespace: databases
spec:
  storageClassName: linode-block-storage-retain
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 25Gi
