authors:
  joe:
    name: Joe Banks
    description: DevOps Team Member
    avatar: https://github.com/jb3.png
  jc:
    name: Johannes
    description: Caretaker
    avatar: https://github.com/pydis-bot.png
