- name: Disable UFW  # noqa
  community.general.ufw:
    state: disabled
  tags:
    - role::ufw
  ignore_errors: true  # subsequent deploys

- name: Uninstall UFW
  apt:
    name: ufw
    state: absent
    purge: true

- name: Purge UFW files
  file:
    path: /etc/ufw
    state: absent
