---
- name: Install fail2ban package
  package:
    name: fail2ban
    state: present
  tags:
    - role::fail2ban

- name: Copy fail2ban config
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "0644"
  tags:
    - role::fail2ban
  notify:
    - Reload fail2ban

- name: Enable fail2ban service
  service:
    name: fail2ban
    state: started
    enabled: true
  tags:
    - role::fail2ban
