---
# https://kubernetes.io/docs/reference/ports-and-protocols/
- name: install rules for private Kubernetes control plane nodes services
  community.general.ufw:
    rule: allow
    proto: tcp
    port: "{{ item[0].ports }}"
    comment: "{{ item[0].comment }}"
    src: "{{ item[1] }}"
  with_nested:
    - - ports: 2379:2380
        comment: etcd server client API
      - ports: 10250
        comment: Kubelet API
      - ports: 10259
        comment: kube-scheduler
      - ports: 10257
        comment: kube-controller-manager
    - "{{ groups['k8s_cluster'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) }}"

- name: install rules for public Kubernetes control plane nodes services
  community.general.ufw:
    rule: allow
    proto: tcp
    port: "{{ item.ports }}"
    comment: "{{ item.comment }}"
  with_items:
    - ports: 6443
      comment: Kubernetes API server
