postgres_version: "15"
postgres_daemon: "postgresql@{{ postgres_version }}-main"
postgres_user: "postgres"

postgres_users:
  - name: pinnwand
    password: "{{ vault_postgres_user_passwords.pinnwand }}"
    roles:

  - name: blackbox
    password: "{{ vault_postgres_user_passwords.blackbox }}"
    roles:
      - pg_read_all_data


postgres_databases:
  - name: pinnwand
    owner: pinnwand
