postgres_version: "15"
postgres_daemon: "postgresql@{{ postgres_version }}-main"
postgres_user: "postgres"

postgres_users:
  - name: pinnwand
    password: "{{ vault_postgres_user_passwords.pinnwand }}"
    roles:

  - name: blackbox
    password: "{{ vault_postgres_user_passwords.blackbox }}"
    roles:
      - pg_read_all_data

  - name: bitwarden
    password: "{{ vault_postgres_user_passwords.bitwarden }}"
    roles:

  - name: blackknight
    password: "{{ vault_postgres_user_passwords.blackknight }}"
    roles:

  - name: codejam_management
    password: "{{ vault_postgres_user_passwords.codejam_management }}"
    roles:

postgres_hba_rules:
  - conn_type: host
    database: pinnwand
    user: pinnwand
    address: all
    method: scram-sha-256

  - conn_type: host
    database: all
    user: blackbox
    address: all
    method: scram-sha-256

  - conn_type: host
    database: bitwarden
    user: bitwarden
    address: all
    method: scram-sha-256

  - conn_type: host
    database: blackknight
    user: blackknight
    address: all
    method: scram-sha-256

  - conn_type: host
    database: codejam_management
    user: codejam_management
    address: all
    method: scram-sha-256


postgres_databases:
  - name: pinnwand
    owner: pinnwand
  - name: bitwarden
    owner: bitwarden
  - name: blackknight
    owner: blackknight
  - name: codejam_management
    owner: codejam_management
