nginx_default_cert_name: pydis.wtf

nginx_configs:
  files.pydis.wtf.conf: |
    server {
      listen      443;
      server_name files.pydis.wtf cloud.native.is.fun.and.easy.pydis.wtf;
      root        /var/www/turing;

      location / {
        try_files $uri $uri/ =404;
      }
    }
