apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: databases
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:8.0
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 200m
              memory: 900Mi
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-volume
            - mountPath: /tmp
              name: mongo-temp
          envFrom:
          - secretRef:
              name: mongo-credentials
          securityContext:
            readOnlyRootFilesystem: true
      volumes:
        - name: mongodb-volume
          persistentVolumeClaim:
            claimName: mongodb-storage
        - name: mongo-temp
          emptyDir:
            medium: Memory
