apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: owlcorp-uk
spec:
  secretName: owlcorp.uk-tls
  dnsNames:
    - owlcorp.uk
    - "*.owlcorp.uk"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "merch"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "merch"
