apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pythondiscord-com
spec:
  secretName: pythondiscord.com-tls
  dnsNames:
  - pythondiscord.com
  - '*.pythondiscord.com'
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "apis,forms,monitoring,pixels,prestashop,tooling,web"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "apis,forms,monitoring,pixels,prestashop,tooling,web"
