---
- name: Install SASL dependencies
  package:
    name:
      - sasl2-bin
      - libsasl2-modules
      - libsasl2-modules-ldap
    state: present
  tags:
    - role::sasl

- name: Create SASL authentication daemon user
  user:
    name: sasl
    group: sasl
    system: true
  tags:
    - role::sasl

- name: Copy service user configuration for SASL authentication daemon
  copy:
    src: user.conf
    dest: /etc/systemd/system/saslauthd.service.d/user.conf
    mode: "0640"
    owner: root
    group: root
  tags:
    - role::sasl
  notify:
    - Restart SASL
  register: sasl_systemd_override

- name: Update SASL authentication daemon preferences
  lineinfile:
    path: /etc/default/saslauthd
    regexp: '^{{ item[''key''] }}="'
    line: '{{ item["key"] }}="{{ item["value"] }}"'
    mode: "0644"
    owner: root
    group: root
  loop:
    - key: START
      value: "yes"
    - key: MECHANISMS
      value: ldap
    # Postfix runs in a CHROOT so we need to create the SASLAUTHD socket there
    # to allow Postfix to communicate with it.
    - key: OPTIONS
      value: "-c -m /var/spool/postfix/var/run/saslauthd"
  tags:
    - role::sasl
  notify:
    - Restart SASL

- name: Copy SASL LDAP configuration
  template:
    src: saslauthd.conf.j2
    dest: /etc/saslauthd.conf
    mode: "0640"
    owner: root
    group: sasl
  tags:
    - role::sasl
  notify:
    - Reload SASL

# BEGIN temporary tasks. Can be removed after initial deploy.
- name: Remove Postfix from SASL group
  command: "gpasswd -d postfix sasl"
  register: command_result
  changed_when: "not 'is not a member of' in command_result.stderr"
  failed_when: false
  tags:
    - role::sasl

- name: Remove Postfix SASL configuration
  file:
    path: /etc/postfix/sasl/smtpd.conf
    state: absent
  tags:
    - role::sasl
  notify:
    - Reload postfix
# END temporary tasks. Can be removed after initial deploy.

- name: Enable and start SASL authentication daemon
  systemd_service:
    name: saslauthd
    state: started
    enabled: true
    daemon_reload: "{{ sasl_systemd_override is changed }}"
  tags:
    - role::sasl
