all:
  hosts:
    hopper:
      ansible_host: 192.168.56.2
      ip: 192.168.56.2
      access_ip: 192.168.56.2
    lovelace:
      ansible_host: 192.168.56.3
      ip: 192.168.56.3
      access_ip: 192.168.56.3
    neumann:
      ansible_host: 192.168.56.4
      ip: 192.168.56.4
      access_ip: 192.168.56.4
    ritchie:
      ansible_host: 192.168.56.5
      ip: 192.168.56.5
      access_ip: 192.168.56.5
    turing:
      ansible_host: 192.168.56.6
      ip: 192.168.56.6
      access_ip: 192.168.56.6
  children:
    nginx:
      hosts:
        turing:
    databases:
      hosts:
        lovelace:
