apiVersion: v1
kind: ConfigMap
metadata:
  name: policy-bot-defaults
  namespace: tooling
data:
  policy-bot.yml: |
    # Options for the http server
    server:
      # The listen address and port
      address: "0.0.0.0"
      port: 8080
      # The public URL, used for URL generation when the server is behind a proxy
      public_url: https://policy-bot.pydis.wtf/

    # Options for logging output
    logging:
      # If true, logs are printed in human-readable form. We recommend using
      # "false" to output JSON-formatted logs in production
      text: false
      # Set a minimum logging level threshold
      # Choose from: debug, info, warn, error
      level: debug

    # Options for connecting to GitHub
    github:
      # The URL of the GitHub homepage. Can also be set by the GITHUB_WEB_URL
      # environment variable.
      web_url: "https://github.com"
      # The base URL for v3 (REST) API requests. Can also be set by the
      # GITHUB_V3_API_URL environment variable.
      v3_api_url: "https://api.github.com"
      # The base URL for v4 (GraphQL) API requests. Can also be set by the
      # GITHUB_V4_API_URL environment variable.
      v4_api_url: "https://api.github.com/graphql"
      app:
        # The integration ID of the GitHub app. Can also be set by the
        # GITHUB_APP_INTEGRATION_ID environment variable.
        integration_id: 91554
      oauth:
        # The client ID of the OAuth app associated with the GitHub app. Can also
        # be set by the GITHUB_OAUTH_CLIENT_ID environment variable.
        client_id: "Iv1.5be42b7c960b1ab2"

    # Options for application behavior
    options:
      # The path within repositories to find the policy.yml file
      policy_path: .github/review-policy.yml

      # Policy to use when a repository does not explicitly define one
      shared_repository: .github
      shared_policy_path: review-policies/core-developers.yml

      # The context prefix for status checks created by the bot
      status_check_context: "Review requirements"
      # Expand users
      expand_required_reviewers: true
