apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubewatch
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: kubewatch
  template:
    metadata:
      labels:
        app: kubewatch
    spec:
      serviceAccountName: kubewatch
      containers:
      - image: ghcr.io/python-discord/kubewatch:latest
        imagePullPolicy: Always
        name: kubewatch
        volumeMounts:
        - name: config-volume
          mountPath: /root
        envFrom:
        - secretRef:
            name: kubewatch-secrets
        securityContext:
          readOnlyRootFilesystem: true
      restartPolicy: Always
      volumes:
      - name: config-volume
        configMap:
          name: kubewatch-config
