controller:
  # Will add custom headers before sending response traffic to the client according to: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#add-headers
  addHeaders:
    x-powered-by: Joe Banks

  config:
    enable-real-ip: true
    forwarded-for-header: cf-connecting-ip
    generate-request-id: true
    allow-snippet-annotations: true
    annotations-risk-level: Critical
    allow-cross-namespace-resources: true

  extraArgs:
    default-ssl-certificate: "default/pythondiscord.com-tls"

  # This section refers to the creation of the IngressClass resource
  # IngressClass resources are supported since k8s >= 1.18
  ingressClassResource:
    enabled: true
    default: true

  kind: DaemonSet

  service:
    annotations:
      service.beta.kubernetes.io/linode-loadbalancer-throttle: 0
      service.beta.kubernetes.io/linode-loadbalancer-default-proxy-protocol: none

  metrics:
    port: 10254
    enabled: true

    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
