---

- name: Add apt signing key for Grafana repo
  ansible.builtin.apt_key:
    url: "{{ alloy_grafana_signing_key }}"
    state: present
    id: "{{ alloy_grafana_signing_key_fingerprint }}"
    keyring: "/etc/apt/trusted.gpg.d/grafana.gpg"
  tags:
    - role::alloy

- name: Add Grafana apt repository to apt lists
  ansible.builtin.apt_repository:
    repo: "{{ alloy_grafana_repository }}"
    filename: grafana
    state: present
  tags:
    - role::alloy

- name: Install Alloy package from Grafana repository
  package:
    name: alloy
    state: present
  tags:
    - role::alloy

- name: Template Alloy configuration file into Alloy configuration
  template:
    src: config.alloy.j2
    dest: /etc/alloy/config.alloy
    group: root
    owner: root
    mode: "0644"
  tags:
    - role::alloy
  notify:
    - Reload the alloy service

- name: Create service override directory
  file:
    path: /etc/systemd/system/alloy.service.d
    state: directory
    owner: root
    group: root
    mode: "0755"
  tags:
    - role::alloy

- name: Create service dropin with security overrides
  copy:
    src: alloy-override.conf
    dest: /etc/systemd/system/alloy.service.d/override.conf
    owner: root
    group: root
    mode: "0444"
  tags:
    - role::alloy
  notify:
    - Reload the systemd daemon
    - Restart the alloy service

- name: Start and enable the Alloy service
  service:
    name: alloy
    state: started
    enabled: true
  tags:
    - role::alloy
