---
- name: Enable automatic updates in debconf
  ansible.builtin.debconf:
    name: unattended-upgrades
    question: unattended-upgrades/enable_auto_updates
    vtype: boolean
    value: "true"
  tags:
    - role::unattended-upgrades

- name: Install unattended-upgrades
  package:
    name: unattended-upgrades
    state: present
  tags:
    - role::unattended-upgrades

- name: Configure unattended-upgrades
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  loop:
    - regexp: "^(//)?Unattended-Upgrade::Mail .*"
      line: 'Unattended-Upgrade::Mail "devops@pydis.wtf";'
    - regexp: "^(//)?Unattended-Upgrade::Automatic-Reboot .*"
      line: 'Unattended-Upgrade::Automatic-Reboot "true";'
    - regexp: "^(//)?Unattended-Upgrade::Automatic-Reboot-Time .*"
      line: 'Unattended-Upgrade::Automatic-Reboot-Time "02:00";'
  tags:
    - role::unattended-upgrades
