---
- name: Install certbot and certbot Cloudflare plugin
  package:
    name:
      - python3-certbot
      - python3-certbot-dns-cloudflare
    state: present
  tags:
    - role::certbot


- name: Generate Cloudflare credentials file
  copy:
    content: |
      # This file is managed by Ansible
      dns_cloudflare_api_token = {{ certbot_cloudflare_token }}
    dest: /etc/letsencrypt/cloudflare.ini
    owner: root
    group: root
    mode: "0400"
  tags:
    - role::certbot


- name: Create cert-users group
  group:
    name: cert-users
    state: present
  tags:
    - role::certbot


- name: Create certificate directories on hosts
  file:
    path: '{{ item }}'
    recurse: true
    state: directory
    owner: root
    group: cert-users
    mode: "0750" # User rwx, Group rx
  with_items:
    - /etc/letsencrypt/live
    - /etc/letsencrypt/archive
  tags:
    - role::certbot


- name: Request certificates for configured domains
  command: |
    certbot certonly
    --agree-tos
    --non-interactive
    --email {{ certbot_email }}
    --dns-cloudflare
    --dns-cloudflare-credentials /etc/letsencrypt/cloudflare.ini
    -d {{ item }} -d {{inventory_hostname}}.box.pydis.wtf
  args:
    creates: "/etc/letsencrypt/live/{{ item }}/fullchain.pem"
  with_items:
    - "{{ certbot_domains[inventory_hostname] }}"
  tags:
    - role::certbot


- name: Add authorized users to cert-users group
  user:
    name: '{{ item }}'
    groups: cert-users
    append: true
  with_items:
    - "{{ certbot_cert_users[inventory_hostname] }}"
  when: "inventory_hostname in certbot_cert_users"
  tags:
    - role::certbot
