---
- name: Install certbot and certbot Cloudflare plugin
  package:
    name:
      - python3-certbot
      - python3-certbot-dns-cloudflare
    state: present
  tags:
    - role::certbot


- name: Generate Cloudflare credentials file
  copy:
    content: |
      # This file is managed by Ansible
      dns_cloudflare_api_token = {{ certbot_cloudflare_token }}
    dest: /etc/letsencrypt/cloudflare.ini
    owner: root
    group: root
    mode: "0400"
  tags:
    - role::certbot


- name: Create certificate directories on hosts
  file:
    path: /etc/letsencrypt/live
    recurse: true
    state: directory
    owner: root
    group: root
    mode: "0700"
  tags:
    - role::certbot


- name: Request certificates for configured domains
  command: |
    certbot certonly
    --agree-tos
    --non-interactive
    --email {{ certbot_email }}
    --dns-cloudflare
    --dns-cloudflare-credentials /etc/letsencrypt/cloudflare.ini
    -d {{ item }} -d {{inventory_hostname}}.box.pydis.wtf
  args:
    creates: "/etc/letsencrypt/live/{{ item }}/fullchain.pem"
  with_items:
    - "{{ certbot_domains[inventory_hostname] }}"
  tags:
    - role::certbot
