---
- name: Install neomutt
  package:
    name: neomutt
    state: present
  tags:
    - role::neomutt

- name: Configure neomutt folder to standard destination
  copy:
    content: |
      # Ansible managed

      # neomutt will use ~/Mail by default, which with our mailserver
      # being backed by Dovecot we do not support. Hence, we configure
      # IMAP here to allow mail to be read by users logged in via SSH.

      set spoolfile="imaps://mail.pydis.wtf/"
      set imap_user="$USER"

      set folder = $spoolfile
      set postponed  = "+Drafts"
      set record     = "+Sent"
      set trash      = "+Trash"

      mailboxes $spoolfile +Archive $postponed $record +Junk $trash

    owner: root
    group: root
    mode: "0o444"
    dest: /etc/neomuttrc.d/pydis.rc
  tags:
    - role::neomutt
