groups:
- name: nginx
  rules:

  - alert: NGINX4XXRequests
    expr: sum by (service) (rate(nginx_ingress_controller_requests{service!="pixels",status!~"404|444",status=~"^4.."}[1m])) / sum by (service) (rate(nginx_ingress_controller_requests[1m])) > 0.5
    for: 1m
    labels:
      severity: page
    annotations:
      summary: "High rate of 4XX requests for inbound requests"
      description: "Rate of 4XX errors is {{ $value | humanizePercentage }} on service `{{ $labels.service }}`"

  - alert: NGINX5XXRequests
    expr: sum(rate(nginx_ingress_controller_requests{status=~"^5.."}[1m])) by (service) / sum(rate(nginx_ingress_controller_requests{}[1m])) by (service) > 0.5
    for: 1m
    labels:
      severity: page
    annotations:
      summary: "High rate of 5XX requests for inbound requests"
      description: "Rate of 5XX errors is {{ $value | humanizePercentage }} on service `{{ $labels.service }}`"

  - alert: NGINXP99Timing
    expr: histogram_quantile(0.99, sum by(host, service, le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{service!~"(grafana|metabase|prestashop-svc)", host!="pydis-api.default.svc.cluster.local"}[5m]))) > 3 and on(service) increase(nginx_ingress_controller_requests[5m]) > 10
    for: 5m
    labels:
      severity: page
    annotations:
      summary: "Request timing P99 has been over 3 seconds for 5 minutes"
      description: "Requests to service {{ $labels.host }} (to service {{ $labels.service }}) have taken over 3 seconds (P99) to complete."
