groups:
- name: redis
  rules:
  - alert: redis/down
    expr: redis_up == 0
    for: 1m
    labels:
      severity: page
    annotations:
      summary: "Redis is offline"
      description: "Redis Exporter cannot connect to Redis."

  - alert: redis/oom
    expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.9
    for: 0m
    labels:
      severity: page
    annotations:
      summary: "Redis is approaching it's memory limit"
      description: "Redis is currently using {{ $value | humanizePercentage }} of configured memory."
