---
- name: Install munin packages
  package:
    name:
      - munin
      - munin-node
      - spawn-fcgi
      # Plugin packages
      - libdbd-pg-perl
    state: present
  tags:
    - role::munin

- name: Template munin configuration file
  template:
    src: munin.conf.j2
    dest: /etc/munin/munin.conf
    owner: root
    group: root
    mode: "0444"
  tags:
    - role::munin
