---
- name: Install munin packages
  package:
    name:
      - munin
      - munin-node
      - spawn-fcgi
      # Plugin packages
      - libdbd-pg-perl
    state: present
  tags:
    - role::munin

- name: Template munin configuration file
  template:
    src: munin.conf.j2
    dest: /etc/munin/munin.conf
    owner: root
    group: root
    mode: "0444"
  tags:
    - role::munin

- name: Template munin-node configuration file
  template:
    src: munin-node.conf.j2
    dest: /etc/munin/munin-node.conf
    owner: root
    group: root
    mode: "0444"
  tags:
    - role::munin
  notify:
    - Restart munin-node service

- name: Enable non-default munin plugins
  file:
    src: "/usr/share/munin/plugins/{{ item.src }}"
    dest: "/etc/munin/plugins/{{ item.dest | default(item.src) }}"
    state: link
  loop:
    # SpamAssassin
    - src: spamstats
    # Nginx
    - src: nginx_request
    - src: nginx_status
    # Postfix
    - src: postfix_mailstats
    - src: postfix_mailqueue
    - src: postfix_mailvolume
    # PostgreSQL
    - src: postgres_size_
      dest: postgres_size_metricity
    - src: postgres_size_
      dest: postgres_size_site
    - src: postgres_size_
      dest: postgres_size_ALL
    - src: postgres_xlog
    - src: postgres_autovacuum
    - src: postgres_bgwriter
    - src: postgres_checkpoints
    - src: postgres_connections_db
    - src: postgres_users
    - src: postgres_xlog
  tags:
    - role::munin
  notify:
    - Restart munin-node service

- name: Copy custom munin plugins
  copy:
    content: "{{ item.value }}"
    dest: /etc/munin/plugins/{{ item.key }}
    owner: root
    group: root
    mode: "0555"
  loop_control:
    label: "{{ item.key }}"
  loop: "{{ munin_node_custom_plugins | dict2items }}"
  tags:
    - role::munin

- name: Disable some unneeded plugins
  file:
    path: "/etc/munin/plugins/{{ item }}"
    state: absent
  loop:
    - squeezebox_albums
    - squeezebox_artists
    - squeezebox_genres
    - squeezebox_signalstrength
    - squeezebox_songs
    - squeezebox_volume
    - squeezebox_years
  tags:
    - role::munin
  notify:
    - Restart munin-node service
