name: Deploy DNS to providers

on:
  push:
    branches:
      - main
jobs:
  octodns-sync:
    environment: production
    name: Sync latest changes to DNS providers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python Dependencies
        uses: HassanAbouelela/actions/setup-python@setup-python_v1.4.2
        with:
          python_version: '3.12'
          install_args: --only dns
      - uses: solvaholic/octodns-sync@main
        with:
          config_path: dns/production.yaml
          doit: '--doit'
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
