name: Deploy DNS to providers

on:
  push:
    branches:
      - main
    paths:
      - 'dns/**'
jobs:
  octodns-sync:
    environment: production
    name: Sync latest changes to DNS providers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          activate-environment: true

      - name: Install dependencies
        run: uv sync --frozen --only-group dns

      - uses: solvaholic/octodns-sync@main
        with:
          config_path: dns/production.yaml
          doit: '--doit'
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
