name: Test documentation
on:
  pull_request:

jobs:
  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
