name: Test documentation
on:
  pull_request:

jobs:
  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.124.0'
          extended: true
      - name: Run hugo
        run: |
          cd docs
          hugo --panicOnWarning --renderToMemory
