name: Test documentation
on:
  pull_request:

jobs:
  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install hugo
        run: |
          sudo apt-get update -y
          sudo apt-get install -y hugo
      - name: Run hugo
        run: |
          cd docs
          hugo --panicOnWarning --renderToMemory
