name: PR Thanker

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  thanks:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Comment on PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "Thanks!"
          check_for_duplicate_msg: true
